### ISSUE TITLE
Lichess Speedrun

### ISSUE THREAD

**Issue by Notproffesionalcoder** [dignissimus/lichess-speedrun#10]
Hi! could you tell me what is this exactly

**Comment by dignissimus** [comment]
Hey! It's WIP and doesn't yet work, but it will allow people to perform speedruns on lichess by maintaining a virtual rating on the client and replacing your normal rating on the site. This means you can play casual games and it'll be as if the game is rated.

Currently, there are a few problems with speedrunning on lichess. Firstly to get a low rating you'll need to sandbag, which is against site rules. Secondly Glicko2 makes speedrunning difficult as it's designed to very quickly increase your rating when it's too low for your skill level when you start, lowering the rating deviation to counteract this requires further sandbagging. It's also not fair on other players to play rated games with a false or inaccurate rating.

To fix these, the virtual rating can be set at an initial value, say 600, and the user can play causal games against opponents rated around 600 to increase their rating as if they were playing rated games. I'd like to also integrate it with twitch so streamers can play viewers in the game pool.

I'd like the replace the functionality of the quick-pair buttons (shown in the image below) so they search for casual games at the virtual rating.

If there's anything you think should be explained that I haven't, feel free to ask questions and also to edit the `README.md` file to add more content.

![quick pair](https://user-images.githubusercontent.com/18627392/127216260-469e78d1-2eeb-4ba1-b924-f1da450a48cc.png)
